# Generated by Django 4.0.4 on 2022-05-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_country_post_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.country'),
        ),
    ]
