# Generated by Django 4.0.4 on 2022-06-18 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_alter_country_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(help_text='Choose a country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.country', verbose_name='Country about which post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posts date and time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text="Write what's on your mind?", verbose_name='Posts text'),
        ),
    ]
