# Generated by Django 4.0.4 on 2022-06-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Choose image for your post', null=True, upload_to='posts/', verbose_name='Image'),
        ),
    ]
