# Generated by Django 4.0.4 on 2022-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(verbose_name='Write a comment...'),
        ),
    ]
